# default configuration
# default parameters
baseURL = "https://broig-test.netlify.app"
languageCode = "es-es"
summaryLength = "10"
theme = "kross-hugo"
title = "Bernat Roig"
# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2

[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4

[params]
address = ""
author = "Bernat Roig"
copyright = "Copyright &copy; 2021 a theme by [gethugothemes](https://gethugothemes.com)"
description = "Portfolio personal Bernat Roig"
email = "bernatroig@bernatroig.es"
google_analytics_id = ""
home = "Home"
logo = ""
phone = "+34 634 516 953"
theme_color = "#41228e"
# theme color
[params.contact]
enable = true
form_action = "#"

[params.cookies]
enable = true
expire_days = "2"

[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
link = "plugins/slick/slick.css"

[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"

[[params.plugins.js]]
link = "plugins/google-map/map.js"

[params.preloader]
enable = false
preloader = "images/preloader.gif"

[[params.social]]
URL = "#"
icon = "ti-facebook"

[[params.social]]
URL = "#"
icon = "ti-instagram"

[[params.social]]
URL = "#"
icon = "ti-dribbble"

[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
